name: GH CI

on: 
  push:
    branches:
          - "*"
    tags:
      - "v*"
jobs:
  simple:
    runs-on: ubuntu-latest
  
    steps:
      - name: HW
        run: echo -n -e "HELLO\n !\n World!" > text.txt
