name: GH CI

on: 
  push:
    branches:
          - "*"
    tags:
      - "v*"
jobs:
  simple:
    runs-on: ubuntu-latest
  
    steps:
      - name: README
        run: echo "version=$(cat README.md)" >> $GITHUB_OUTPUT
