name: GH CI

on: 
  push:
    branches:
          - "*"
    tags:
      - "v*"
jobs:
  simple:
    name: simple_name
    runs-on: ubuntu-latest
  
    steps:
      - name: my-step
        run: echo "Hello World!"
